name: dio_ali_sign
description: dio_ali_sign is a Dio interceptor that sign aliyun api gateway request,easy to use.
version: 1.0.9

homepage: https://github.com/csdntm/dio_ali_sign

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  meta: ^1.2.1

  ali_cloudapi_sign: ^1.0.0

dev_dependencies:
  test: ^1.15.2
  pretty_dio_logger: ^1.1.1
