name: dio_ali_sign
description: dio_ali_sign is a Dio interceptor that sign aliyun api gateway request,easy to use.
version: 1.1.0

homepage: https://github.com/csdntm/dio_ali_sign

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  meta: ^1.1.8
  ali_cloudapi_sign: ^1.0.12

dev_dependencies:
  test: ^1.15.2
  pretty_dio_logger: ^1.1.1
  pedantic: ^1.9.0
