name: Publish package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: hjue/actions-flutter-pub-publisher@v1.3.1
        env:
          gatewayHosts: ${{ secrets.GATEWAYHOSTS }}
          gatewayAppkey: ${{ secrets.GATEWAYAPPKEY }}
          gatewayAppsecret: ${{ secrets.GATEWAYAPPSECRET }}
          urlGet: ${{ secrets.URLGET }}
          urlPost: ${{ secrets.URLPOST }}
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: false
          dry_run: false
